title: Kumaresan Periyasamy
logo: "/profile.png?raw=true"
description: > 
 Full Stack Developer
  <br><br>
  <a href="mailto:cpkumaresan1@gmail.com">cpkumaresan1@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/cpkumaresan1/">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/cpkumaresan1/">Gihub</a> 
theme: jekyll-theme-minimal
